version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile.Bot
    image: thebottle/leviathan-bot
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.Web
    image: thebottle/leviathan-web
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.Worker
    image: thebottle/leviathan-worker