FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Leviathan.Web/Leviathan.Web.csproj", "Leviathan.Web/"]
COPY ["Leviathan.Core/Leviathan.Core.csproj", "Leviathan.Core/"]
RUN dotnet restore "Leviathan.Web/Leviathan.Web.csproj"
COPY . .
WORKDIR "/src/Leviathan.Web"
RUN dotnet build "Leviathan.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Leviathan.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Leviathan.Web.dll"]
