// <auto-generated />
using System;
using Leviathan.Core.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leviathan.Core.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20220215172225_AddingExpiresToJobs")]
    partial class AddingExpiresToJobs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Leviathan.Core.Models.Database.Alliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AllianceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alliance_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("alliances");
                });

            modelBuilder.Entity("Leviathan.Core.Models.Database.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discord_user_id");

                    b.Property<int>("EsiAllianceID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esi_alliance_id");

                    b.Property<int>("EsiCharacterID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esi_character_id");

                    b.Property<string>("EsiCharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("esi_character_name");

                    b.Property<int>("EsiCorporationID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esi_corporation_id");

                    b.Property<bool>("EsiSsoStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esi_sso_status");

                    b.Property<string>("EsiTokenAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("esi_sso_access_token");

                    b.Property<DateTime>("EsiTokenExpiresOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("esi_sso_expires_on");

                    b.Property<string>("EsiTokenRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("esi_sso_refresh_token");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_state");

                    b.HasKey("Id");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("Leviathan.Core.Models.Database.Corporation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AllianceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alliance_id");

                    b.Property<int>("CorporationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("corporation_id");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("corporations");
                });
#pragma warning restore 612, 618
        }
    }
}
